# Generated by Django 2.0 on 2019-06-27 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('landmark_1', models.CharField(blank=True, max_length=200, null=True)),
                ('landmark_2', models.CharField(blank=True, max_length=200, null=True)),
                ('landmark_3', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('flat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('sqft_area', models.PositiveIntegerField(default=0)),
                ('rent', models.PositiveIntegerField(default=0)),
                ('flat_type', models.CharField(blank=True, choices=[('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('Studio', 'Studio')], max_length=100, null=True)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('ec_acc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.Building')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('name', 'address')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('building', 'flat_number')},
        ),
    ]
